name: "Build"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: "Windows"
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Build"
        run: |
          python -m pip install pyinstaller
          pyinstaller --noconfirm client.spec
          python manifest.py

      - name: "Download FFmpeg"
        uses: robinraju/release-downloader@v1.10
        with:
          repository: 'BtbN/FFmpeg-Builds'
          fileName: 'ffmpeg-master-latest-win64-gpl.zip'
          out-file-path: 'dist'
          latest: true
          extract: true

      - name: "Move FFmpeg"
        run: |
          mv dist/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe dist/ffmpeg.exe
          ls dist

      - name: "Inno Setup"
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: install-win.iss
          options: "/DMyAppVersion=${{ github.ref_name }}"

      - name: "Debug"
        run: |
          ls -R out

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: install-win
          path: out

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  linux:
    name: "Linux"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Download FFmpeg"
        uses: robinraju/release-downloader@v1.10
        with:
          repository: 'BtbN/FFmpeg-Builds'
          fileName: 'ffmpeg-master-latest-linux64-gpl.tar.xz'
          out-file-path: 'dist'
          latest: true

      - name: "Move FFmpeg"
        run: |
          ls dist
          tar -xf dist/ffmpeg-master-latest-linux64-gpl.tar.xz ffmpeg-master-latest-linux64-gpl/bin/ffmpeg -C dist
          mv dist/ffmpeg-master-latest-linux64-gpl/bin/ffmpeg dist/ffmpeg
          ls dist

      - name: "Debian Package"
        run: |
          python manifest.py
          bash install-linux.sh

      - name: "Debug"
        run: |
          ls -R

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: install-linux
          path: out

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
